service: wordle-backend

frameworkVersion: "4"

provider:
  name: aws
  runtime: python3.10
  region: us-east-1
  stage: prod

functions:
  api:
    handler: app/handler.handler
    events:
      - http:
          path: /api/guess
          method: post
          cors: true

package:
  patterns:
    - api/**
    - app/**
    - requirements.txt

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: false
    slim: true
    pythonBin: python3.10